#!/bin/bash
CEPH_CLUSTER=${CEPH_CLUSTER:-ceph}
CONSUL_SERVER=${CONSUL_SERVER:-http://localhost:8500}

exec confd -node $CONSUL_SERVER -backend confd -config-file /etc/confd/confd.toml -prefix /ceph/$CEPH_CLUSTER
