#!/bin/bash
ETCD_PORT=${ETCD_PORT:-4001}
ETCD=${ETCD:-http://$HOST:$ETCD_PORT}
CEPH_CLUSTER=${CEPH_CLUSTER:-ceph}
ETCD_PATH="/ceph/$CEPH_CLUSTER"

exec confd -node $ETCD -config-file /etc/confd/confd.toml -prefix $ETCD_PATH
