#!/bin/bash
# Borrows heavily from Seán C. McCord's https://github.com/Ulexus/docker-ceph repository

set -e

CEPH_CLUSTER=${CEPH_CLUSTER:-ceph}
NUM_STORES=${NUM_STORES:-3}
PG_NUM=${PG_NUM:-128} # default for 3 OSDs
HOSTNAME=`hostname`
CONSUL_SERVER=${CONSUL_SERVER:-http://127.0.0.1:8500}

function kv_set {
    curl -sT <(echo $2) "$CONSUL_SERVER/v1/kv/ceph/$CEPH_CLUSTER/$1"
}

function kv_set_file {
    curl -sT $2 "$CONSUL_SERVER/v1/kv/ceph/$CEPH_CLUSTER/$1"
}

function kv_set_once {
    curl -sT <(echo $2) "$CONSUL_SERVER/v1/kv/ceph/$CEPH_CLUSTER/$1?cas=0" | grep -q true
}

function kv_set_default {
    curl -sT <(echo $2) "$CONSUL_SERVER/v1/kv/ceph/$CEPH_CLUSTER/$1?cas=0" > /dev/null
}

function kv_get {
    curl -sf $CONSUL_SERVER/v1/kv/ceph/$CEPH_CLUSTER/${1}?raw
}

if ! kv_get setup/complete > /dev/null ; then
  echo -n "Ceph hasn't yet been deployed. "
  if kv_set_once setup/lock $HOSTNAME || [[ $(kv_get setup/lock) == "$HOSTNAME" ]] ; then
    echo "Bootstrapping..."

    # these are templated in ceph.conf
    kv_set_default size ${NUM_STORES}
    kv_set_default minSize 1
    kv_set_default pgNum ${PG_NUM}
    kv_set_default delayStart 15

    ceph-authtool /etc/ceph/ceph.client.admin.keyring --create-keyring --gen-key -n client.admin --set-uid=0 --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow'
    kv_set_file keyrings/client.admin /etc/ceph/ceph.client.admin.keyring

    ceph-authtool /etc/ceph/ceph.mon.keyring --create-keyring --gen-key -n mon. --cap mon 'allow *'
    kv_set_file keyrings/monitor < /etc/ceph/ceph.mon.keyring >/dev/null

    fsid=$(uuidgen)
    kv_set fsid ${fsid}

    # Generate initial monitor map
    monmaptool --create --add ${HOSTNAME} ${HOST} --fsid ${fsid} /etc/ceph/monmap

    # mark setup as complete
    echo "Bootstrapping complete!"
    kv_set setup/complete yup
  else
      echo "Waiting for another monitor to complete bootstrapping..."
    until kv_get setup/complete > /dev/null; do
      echo "Waiting..."
      sleep 5
    done
  fi
fi

until confd -onetime -node $CONSUL_SERVER -config-file /etc/confd/confd.toml -prefix /ceph/$CEPH_CLUSTER >/dev/null; do
  echo "Waiting for confd to write initial templates..."
  sleep 5
done

# If we don't have a monitor keyring, this is a new monitor
if [ ! -e /var/lib/ceph/mon/ceph-${HOSTNAME}/keyring ]; then
  if [ ! -f /etc/ceph/monmap ]; then
    ceph mon getmap -o /etc/ceph/monmap
  fi

  # Import the client.admin keyring and the monitor keyring into a new, temporary one
  ceph-authtool /tmp/ceph.mon.keyring --create-keyring --import-keyring /etc/ceph/ceph.client.admin.keyring
  ceph-authtool /tmp/ceph.mon.keyring --import-keyring /etc/ceph/ceph.mon.keyring

  # Make the monitor directory
  mkdir -p /var/lib/ceph/mon/ceph-${HOSTNAME}

  # Prepare the monitor daemon's directory with the map and keyring
  ceph-mon --mkfs -i ${HOSTNAME} --monmap /etc/ceph/monmap --keyring /tmp/ceph.mon.keyring

  # Clean up the temporary key
  rm /tmp/ceph.mon.keyring
fi

exec /usr/bin/ceph-mon -d -i ${HOSTNAME} --public-addr ${HOST}:6789
